export const GET_POSTS_SUCCESS="GET_POSTS_SUCCESS"


export const LOGIN_REQUEST= 'USERS_LOGIN_REQUEST'
export const LOGIN_SUCCESS= 'USERS_LOGIN_SUCCESS'
export const LOGIN_FAILURE= 'USERS_LOGIN_FAILURE'

export const LOGOUT= 'USERS_LOGOUT'