export const GET_POSTS_SUCCESS="GET_POSTS_SUCCESS"
export const GET_USER_POSTS_SUCCESS="GET_USER_POSTS_SUCCESS"


export const LOGIN_REQUEST= 'USERS_LOGIN_REQUEST'
export const LOGIN_SUCCESS= 'USERS_LOGIN_SUCCESS'
export const LOGIN_FAILURE= 'USERS_LOGIN_FAILURE'

export const LOGOUT= 'USERS_LOGOUT'


export const REGISTER_REQUEST= 'USERS_REGISTER_REQUEST'
export const REGISTER_SUCCESS= 'USERS_REGISTER_SUCCESS'
export const REGISTER_FAILURE= 'USERS_REGISTER_FAILURE'



export const SHARE_POST_SUCCESS= 'SHARE_POST_SUCCESS'
export const SHARE_POST_FAILURE= 'SHARE_POST_FAILURE'

export const DELERE_POST= 'DELETE_POST'

export const ADD_COMMENT='ADD_COMMENT'
export const DELETE_COMMENT='DELETE_COMMENT'
export const EDIT_COMMENT='EDIT_COMMENT'
export const GET_USER_COMMENTS="GET_USER_COMMENTS"

export const LIKE='LIKE'
export const DISLIKE='DISLIKE'